trino:
  target: dev
  outputs:
    dev:
      type: trino
      user: trino
      host: trino
      port: "8080"
      database: iceberg
      schema: project
      http_scheme: http
      threads: 1
      session_properties:
        query_max_run_time: 5d
